# Generated by Django 4.2.6 on 2023-10-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_description', models.TextField()),
                ('dish_image', models.ImageField(upload_to='dish')),
            ],
        ),
    ]
