# Generated by Django 4.2.6 on 2023-10-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish_user_alter_dish_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
