# Generated by Django 4.2.6 on 2023-10-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('esal', models.FloatField()),
                ('eaddress', models.TextField()),
            ],
        ),
    ]
