# Generated by Django 4.2.6 on 2023-10-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0003_alter_employee_ename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.TextField(max_length=100)),
                ('car_speed', models.IntegerField()),
                ('car_price', models.FloatField()),
                ('car_description', models.TextField()),
                ('car_image', models.ImageField(upload_to='car')),
            ],
        ),
    ]
