# Generated by Django 4.2.6 on 2023-10-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0004_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_price',
            field=models.IntegerField(),
        ),
    ]
