# Generated by Django 4.2.6 on 2023-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0005_alter_car_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.TextField(max_length=500),
        ),
    ]
