# Generated by Django 4.2.7 on 2023-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummiez', '0004_alter_books_author_alter_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
